### ISSUE TITLE
havent given the database file

### ISSUE THREAD

**Issue by santoshraju621** [oxenfree/CMS#1]
hi please give me the database file i have installed but need the sql file to create database and connect the application.

please help me to solve

**Comment by oxenfree** [comment]
I don't have a database file. This is an old school project that was never meant to be used in production.

**Comment by oxenfree** [comment]
One of my old classmates found the SQL dump for our final project. Attached here. 
[holidayDBDump2016-03-09.txt](https://github.com/oxenfree/CMS/files/1468692/holidayDBDump2016-03-09.txt)

**Comment by oxenfree** [comment]
The database is called "holiday" because it was for a holiday gifts store. The database can be renamed to anything you'd like.

**Comment by santoshraju621** [comment]
ok thanks for giving the dump if you have any cms projects related to spring and hibernate please provide me a link to download

**Comment by santoshraju621** [comment]
some of database tables are missing on that dump

**Comment by oxenfree** [comment]
Sorry, that's the best I have.

**Comment by santoshraju621** [comment]
ok Thankyou i have created the missing tables and it is now working properly

**Comment by oxenfree** [comment]
Can you dump your SQL file and make a PR to this repo?

**Comment by santoshraju621** [comment]
Here is The Database File i Worked on the Username to login is: admin
 and password is: admin
[holiday.txt](https://github.com/oxenfree/CMS/files/1487348/holiday.txt)
